name = "NLPModelsTest"
uuid = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
version = "0.10.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LinearAlgebra = "1.10"
NLPModels = "0.21.6"
NLPModelsModifiers = "0.7"
Printf = "1.10"
SparseArrays = "1.10"
Test = "1.10"
julia = "1.10"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[targets]
test = ["CUDA", "Distributed"]
